### ISSUE TITLE
minor typo in vertex_animation.py

### ISSUE THREAD

**Issue by lockphase** [JoshRBogart/unreal_tools#11]
The class definition is ```class OBJECT_OT_ProcessAnimMeshes(bpy.types.Operator):```
The register and unregistering is 
```bpy.utils.register_class(OBJECT_OP_ProcessAnimMeshes)```
```bpy.utils.unregister_class(OBJECT_OP_ProcessAnimMeshes)```

**Comment by JoshRBogart** [comment]
Thank you for bringing this to my attention. The issue should be solved now.
