### ISSUE TITLE
We need to support blender version 2.8x！please！

### ISSUE THREAD

**Issue by kezhihao** [JoshRBogart/unreal_tools#9]
We need to support blender version 2.8x！please！

**Comment by MWallace3D** [comment]
Hi. There's a pull request with updated 2.80 files. 
[https://github.com/JoshRBogart/unreal_tools/pull/8/files](url)

**Comment by Sturmlicht** [comment]
Hey MWallace3D, I did install your fork, with the 2.8 fix. However I have troubles finding the options. To convert my animation of a morph shape animated cube into a texture. 
I am new to blender and to this script. I probably miss something. Here screenshots from my preferences and property panel.
![image](https://user-images.githubusercontent.com/39851803/68302591-a61f6a00-00a2-11ea-8511-b96fc90dad06.png)
![image](https://user-images.githubusercontent.com/39851803/68302630-b20b2c00-00a2-11ea-90f4-954787e0afd8.png)

**Comment by Sturmlicht** [comment]
Ok, I seemed to have the problem because of the file path blender was using, however I changed it so it installed the zip in the correct place. The user here with the same problem fixed the issue by moving the io_... folder to the correct place, However I cannot find an io_ folder. :/ 

here the link to the issue of that other user with installing add ons
https://blenderartists.org/t/blender-2-8-trying-to-install-addons-with-blender-on-d-drive-still-installs-to-c-drive-folder/1164434/4

**Comment by Sturmlicht** [comment]
Ok,. after rezipping your files and importing them to the correct path, I could finally find the Unreal tools, It seems the "Tool Shelf" is the one you can open by pressing N in the 3D viewport Panel 

Leaving this here for others, in case they do also encounter troubles 
![image](https://user-images.githubusercontent.com/39851803/68311255-95c2bb80-00b1-11ea-89f7-27b26e413424.png)

**Comment by Sturmlicht** [comment]
and it seems I do not have the full functionality as described here https://forums.unrealengine.com/community/work-in-progress/110003-vertex-animation-script-for-blender-3d-users

When pushing the "Pack Morph Tagets" I do not seem to get any results to export. Any help and answer would be apprechiated :)

**Comment by Sturmlicht** [comment]
Hey, with the help of someone more familiar with Blender, I made this work. Get the fork from MWallace3D and only install the two .py files with 280 - do not load a previous created scene and you can work with the tutorial :) also export the "Export Mesh" that is generated, not the Mesh you created before the animation ;) 

I am very happy that this tool exists and I am excited to make some stuff with it. So thanks to everyone contributed to this! You are awesome!
